seed: 123
context_length: 20
epochs: 600
model_type: "reward_conditioned"
num_steps: 500000
num_buffers: 50
sample_iteration: 1
batch_size: 128
horizon: 20
env: "GoToObjMazeS4"
name: "reward_uni_door_close_N4"
stochastic: true
leap: false
action_horizon: 1
noise: "masking"
exploration_loss: "entropy"
learning_rate: 1e-4
adam_eps: 1e-06
adam_beta1: 0.9
adam_beta2: 0.999
rollout: 20
num_workers: 16
exploration_loss_coeff: 0.000005
exploration_loss_coeff_end: -1
value_loss_coeff: 0.5
loss_type: "mean"
